name: Test and Validate

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install CDK dependencies
      run: npm install

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Lint frontend
      run: |
        cd frontend
        npm run lint

    - name: Build frontend
      run: |
        cd frontend
        npm run build

    - name: Build CDK
      run: npm run build

    - name: Run CDK tests
      run: npm test

    - name: CDK synth
      run: npx cdk synth
